
services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
    networks:
      - app_network

  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
      - php
    networks:
      - app_network

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "root"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app_network

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      APP_ENV: local
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER:
    ports:
      - "8082:8080"
    networks:
      - app_network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

networks:
  app_network:

###< doctrine/doctrine-bundle ###
volumes:
###> doctrine/doctrine-bundle ###
  database_data:

###< doctrine/doctrine-bundle ###
